services:
  web-database:
    container_name: "web-database"
    image: "postgres:16.6"
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT-5432}:5432"
    volumes:
      - "web-postgres-data:/var/lib/postgresql/data"

volumes:
  web-postgres-data:
