/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Customergender = "man" | "other" | "woman"

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface Category {
  id: Generated<number>
  title: string
}

export interface Customer {
  address: string
  city: string
  email: string
  firstName: string
  gender: Customergender
  id: Generated<number>
  lastName: string
  password: string
  phone: string
  zipCode: string
}

export interface Product {
  categoryId: number
  description: string
  id: Generated<number>
  imageURL: string
  priceCents: number
  title: string
}

export interface DB {
  Category: Category
  Customer: Customer
  Product: Product
}
