name: "ci"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.2.2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.1.0"
        with:
          node-version: "22.x"
          cache: "npm"

      - run: "npm clean-install"

      - run: "node --run lint:typescript"
      - run: "node --run lint:eslint"
      - run: "node --run lint:prettier"
      - run: "node --run build"
      - run: "node --run test"
